site_name: Syncra Engine Documentation
site_url: https://mydomain.org/mysite
nav:
  - Home: "index.md"
  - 'Getting Started':
    - Installation: "getting_started/installation.md"

theme:
  name: material
  features:
    - content.code.annotate
markdown_extensions:
  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # Code Blocks
  - pymdownx.highlight:
      	anchor_linenums: true
      	line_spans: __span
      	pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # Tabs
  - pymdownx.tabbed:
	alternate_style: true
  # Icons
  - attr_list
  - pymdownx.emoji:
	emoji_index: !!python/name:material.extensions.emoji.twemoji
	emoji_generator: !!python/name:material.extensions.emoji.to_svg
