# This workflow automatically updates the CREDITS.md file when a commit is pushed to main

name: Update CREDITS.md

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-credits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate contributor list
        run: |
          echo "## Contributors" > contributors.tmp
          echo "" >> contributors.tmp
          curl -s https://apt.github.com/repos/${{ github.repository }}/contributors |
          jq -r '.[] | "- [\(.login)](https://github.com/\(.login))"' >> contributors.tmp

      - name: Merge CREDITS.md with contributor list
        run: |
          awk '/## Contributors/{exit}1' CREDITS.md > credits.top
          cat credits.top contributors.tmp > CREDITS.MD

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update CREDITS.md with latest contributors"
